### ISSUE TITLE
[RAM] [META] UX: Rule Enhancements

### ISSUE THREAD

**Issue by mdefazio** [elastic/design-system-team#145]
## Meta issue for all rule enhancements

- [ ] https://github.com/elastic/kibana/issues/136017
- [x] https://github.com/elastic/kibana/issues/126601
- [x] https://github.com/elastic/kibana/pull/135643
- [x] https://github.com/elastic/kibana/pull/134763
- [x] https://github.com/elastic/kibana/issues/133570
- [x] https://github.com/elastic/kibana/issues/132860
