### ISSUE TITLE
[Meta] Elastic Design System Documentation

### ISSUE THREAD

**Issue by daveyholler** [elastic/design-system-team#150]
## Overview
The Elastic Design System is the next, and natural, evolution of EUI. Building upon the success of the EUI component library, the Elastic Design System aims to provide best-in-class documentation of UI components, shared patterns, onboarding, training, and more. Some of the most critical steps towards a truly seamless UX lie in documentation.

## Discovery issues
- [ ] Issues go here

## Design issues
- [ ] Homepage design
- [ ] Header & footer design
- [ ] Search and results pages

---
### Resources
* [Project Brief](https://docs.google.com/document/d/1aBQ9V1Nuc_j2zzAjFJ7Ayx9lxM2ieVWjXItd8wDqQ3s/edit#heading=h.di46imfnv9sw)
* [EUI+ Prototype](https://eui-plus.vercel.app/)
