### ISSUE TITLE
[RAC] [Meta] RAC UI Issue

### ISSUE THREAD

**Issue by mdefazio** [elastic/design-system-team#65]
This issue is meant to track general Alerting issues that are unclear if they fall into RAC, 8.0 RAC, Stack Alerting or Unified Alerting.

| Project Document | Link |
| :---- | :---- |
| Sync Notes - Project | [Doc](https://docs.google.com/document/d/1bcsj838fS73iSK3C8ho5RqFENFHrlTp2ds0VbhMAq4k/edit#heading=h.62ianp4bm4db) |
| Sync Notes - Designers | [Whimsical](https://whimsical.com/rac-designers-weekly-sync-XrFSvJNymPX2XpmcGjUPMk) |
| Mockups | [Figma](https://www.figma.com/file/0905CWHhE2YAgSjIoRzmc9/RAC-Main?node-id=759%3A168005) |
| Wireframes & Flows | [Whimsical](https://whimsical.com/rac-ux-85nJszw4VArkP9LLQWufSS) |
| Glossary | [Doc](https://docs.google.com/document/d/1bcsj838fS73iSK3C8ho5RqFENFHrlTp2ds0VbhMAq4k/edit#heading=h.5swiy4av1ygv) |
| Use Cases & Personas | [Doc](https://docs.google.com/document/d/1bcsj838fS73iSK3C8ho5RqFENFHrlTp2ds0VbhMAq4k/edit#heading=h.4mys0ftmuvn5)
| Competitive Analysis | [Figma](https://www.figma.com/file/mHRS962310YnR9CqPZscdt/Research-Competitor-Alert-Tables?node-id=0%3A1) |
| Project Doc | [Doc](https://docs.google.com/document/d/1bcsj838fS73iSK3C8ho5RqFENFHrlTp2ds0VbhMAq4k/edit?usp=sharing) |

# Progress Outline

_Todo: How do we provide a UI framework for the various solutions to implement so we can insure all are aligned without one or two people creating mockups?_

🟡 - In progress
✅ - Done
🤞 - Stretch goal

## RAC 7.X

**RAC UX Epic, 7.X Remaining Milestones**
https://github.com/elastic/security-team/issues/1299

**RAC Observability 7.15 Checklist**
https://github.com/elastic/kibana/issues/107933

**RAC Security 7.15 Checklist**
https://github.com/elastic/kibana/issues/108071

**Design priorities**

| Component | Design | Stack/Centralized | Security dev | Observability dev | Comment |
| :--- | :--- | :--- | :--- | :--- | :--- |
| **Rule Management** | 🟡 | Legacy w/minor updates | 🤞 | 🤞 | In progress. Design target 7.16; Solution views planned for 8.x | 
| **Rule Detail view** | 🟡 | Remains legacy | 🤞 | 🤞 | In progress. Design target 7.16; Solution views planned for 8.x | 
| **Alert Management** | ✅ | Remains legacy | 🟡 | 🟡 | RAC project near completion. Should review priority with enhancements at the solution level | 
| **Alert Detail Basic View (Flyout)** | ✅ | Remains legacy | ✅  | ✅ | Will need to be updated once detail view is implemented to cleanup items that will move out of this view
| **Case Management** | ✅ | N/A | ✅  | ✅ | RAC done. 8.x iterations needed. | 
| **Case Detail** | ✅ | N/A | ✅  | ✅ | RAC done. 8.x iterations needed. |
| **Case Creation / Selection** | ✅ | N/A | ✅  | ✅ | RAC done. 8.x iterations needed. | 

### Centralized Alerting
There will be some known inconsistencies and future enhancements across the alerting experience. In order to continue working toward and maintaining consistency, a cross-solution team of designers will continue to meet periodically and align on UX changes. The other outstanding lift, not covered by RAC, will be the progression of the existing Stack Management alerting UIs.

| Component | Design | Stack/Centralized | Security | Observability | Comment |
| :--- | :--- | :--- | :--- | :--- | :--- |
| **Rule Management** | -- | -- | -- | -- | Adapt for Observability use case(s); iterate and test | 
| **Rule Detail view** | -- |-- | -- | -- | Adapt for Observability use case(s); iterate and test | 
| **Rule Creation Basic view (Flyout)** | -- | Legacy | -- | Legacy | Needs prioritization; Inconsistency here is a top UX concern coming out of RAC | 
| **Rule Creation Full view** | -- | -- | Legacy | -- | Needs prioritization | 
| **Alert Management** | -- | Legacy | --  | -- | Should review priority with enhancements at the solution level | 
| **Alert Detail Basic View (Flyout)** | -- | Legacy | --  | -- | Will need to be updated once detail view is implemented to cleanup items that will move out of this view | 
| **Alert Detail Full View** | -- | Legacy | Wireframe (RAC) | Wireframe (RAC) | Further design work needed post-RAC views, and then to update Stack view
| **Case Management** | -- | -- | --  | -- | Address post-RAC UX concerns for both Security and Observability. More research needed for Stack to determine user scenario | 
| **Case Detail** | -- | -- | --  | -- | Address post-RAC UX concerns for both Security and Observability. More research needed for Stack to determine user scenario
| **Case Creation / Selection** | -- | -- | --  | -- | Address post-RAC UX concerns for both Security and Observability. More research needed for Stack to determine user scenario | 

---

## General Tasks

- [ ] Consolidate documentation of Alerting terms, workflows and personas
- [x] #80

### Rules
- [x] #68
- [x] #69
- [x] #70

### Alerts
- [ ] #71
- [x] #72
- [x] #73

### Cases
- [x] #74
- [x] #86

### Connectors
Connectors will remain in Stack Management for the foreseeable future. 
- [ ] Update Connector page to break off from Rules
- [ ] Email Connector - MS Exchange and OAuth

### Other
- [ ] [RAC] Ability to create or add an existing connector to a Rule or Case
- [ ] [RAC] RBAC views for Alerts

Additional parallel concepts:
- User Entity
- Investigate flow (Add to Case, View in app)

---

### Issues:
[7.15 UI Update List](https://github.com/elastic/kibana/issues/106585)
