### ISSUE TITLE
[RAC] [Meta] Rule Management UI

### ISSUE THREAD

**Issue by mdefazio** [elastic/design-system-team#68]
## Brief
Provide a unified rules management experience across the Kibana platform, so that rules creation, sort, filter, search, and monitoring are all using the same flow and UI components. 

**Resources**
[Whimsical Brief](https://whimsical.com/rules-9hzETAw6CQGfEWGxriwdVq)
[Security flows](https://docs.google.com/spreadsheets/d/1SGjXVS3gQyRxCN1MF2Pq3pgos3vtfpROqTvi4z-0WiU/edit#gid=1393258675)

- - -

### Required Views:

- [ ] **Onboarding view:** User has no rules built—prompted to install pre-built rules.
- [ ] **Single rule:** Confirm UI works with a single view (if Monitoring is included, consider a single entity and how that effects the visualizations)
- [ ] **Many rules**
- [ ] **No results** from chosen filters
- [ ] **Bulk actions**

_(Rule detail view setup as separate issue)_

### UX flows:
_Ignore the Create new rule flow for this as that is a separate issue._ 
Ref [this doc](https://docs.google.com/spreadsheets/d/1SGjXVS3gQyRxCN1MF2Pq3pgos3vtfpROqTvi4z-0WiU/edit#gid=1393258675) for Security workflows.  Primary ones pulled out below and generalized for Observability purposes.

- [ ] Search or filter to slow-querying rules and bulk disable them
- [ ] Search for rules with similar meta data (tags, tactic, etc.)
- [ ] Search for failing rule and review log history to find issue
- [ ] Confirm a rule was running during specific time, or review log at specific point in time
- [ ] Add / update a new connector to a rule, several rules

- - - 
### 7.16 tasks

- [x] #94
- [x] #95
- [x] #69

### 8.x
- [x] https://github.com/elastic/observability-design/issues/127

## Wireframes
- [Whimsical Rule monitoring v3 (most-up-to-date)](https://whimsical.com/rule-monitoring-v3-65o1vqnn937FxbAuXPWQwL)
- [Whimsical Rule details -> Rule execution logs](https://whimsical.com/rule-details-rule-execution-logs-2vrzGYgLkS8tNRVRQz6EPp)

## Designs
- [Rule management MVP](https://www.figma.com/file/fGlLwahFKcCH9mnkrCz8Dw/7.16-Rule-Management-Version-MVP?node-id=0%3A1)
- [Rule management V1 (Future vision)](https://www.figma.com/file/KEgxx2B9J15i9uH3B50mq2/7.16-Rule-Management-Version-1?node-id=223%3A71326)
- [Rule Details UI](https://www.figma.com/file/UdS0flfEWli1A3Ll0Dq1CF/7.16-Rule-Detail-UI-Version-1?node-id=0%3A1)

**Comment by mdefazio** [comment]
@yiyangliu9286 and myself have created [this doc](https://docs.google.com/document/d/10DrofM9sIFG-3KTJZXi6qOdJ3F1LP-oNz2Z8MdXXve0/edit#) to help align terminology and determine if this is about _both_ management and monitoring.  And if we are including monitoring, what are the cues we should be providing.
