### ISSUE TITLE
[RAC] [Meta] Case Management

### ISSUE THREAD

**Issue by mdefazio** [elastic/design-system-team#74]
## Brief
Provide a unified rules management experience across the Kibana platform, so that rules creation, sort, filter, search, and monitoring are all using the same flow and UI components. 

### Required Views:

- [ ] **Onboarding view:** User has no Cases
- [ ] **Single case:** Confirm UI works with a single case
- [ ] **Many cases:** Confirm UI works with many cases
- [ ] **No results** from chosen filters
- [ ] **Bulk actions**

### UX flows:

_Need to add in primary workflows for this page_

### Updates (7.16)

- [x] #91
- [x] #92

- - - 

## Owners
Monina Nepomuceno
Katrin Freihofner
Michael DeFazio

## Timeline
Initial updates were merged for 7.14
Updates to Case workflow and UI need to be prioritized

## Resources
[Figma](https://www.figma.com/file/0905CWHhE2YAgSjIoRzmc9/RAC-Main?node-id=864%3A202029)
[Cases UX Audit: Katrin](https://whimsical.com/cases-ux-audit-5iVZyZnFvngDxJXgj9c6qh)
[Stack Level Cases - Design Research: Monina](https://docs.google.com/document/d/1nqS9NzjuO9h1pYxlSVMO3nd-uuzdfFPbBQBc89AFsqo/edit)

- - - 

## Wireframes
