### ISSUE TITLE
[RAC] Rule Management: Create base view of Rule management for all 3 solution areas

### ISSUE THREAD

**Issue by mdefazio** [elastic/design-system-team#94]
We need a consistent base for Rule management across Stack, Security and Observability that the various areas can then build upon.

## Tasks: 

- [x] Get confirmation on statuses: Mike P, Gidi/Mike C, Jason/Cyrille: [RFC for statuses](https://docs.google.com/document/d/1mN5fhzaGgUimJB6lnNE5sGW7yyNTlot7asOn2B-S_iM/edit?usp=sharing) 
- [x] How to show muting in UI of Security/Observability rule table
- [x] Auto refresh settings

#### Stack
- [x] Management view based on shared usage
- [x] Empty state

#### Observability
- [x] Management view
- [x] Empty state

#### Security
- [x] Management view for phase 1
- [x] Monitoring edits for phase 1
- [x] Empty states

## Basic functionality
As a user, I need to be able to
- see all rules and navigate to the rule details
- filter, sort, search rules
- edit, delete, mute and disable rules
- bulk actions
- create a new rule
- empty state for view (no rules, no permissions)
- status of rules?

## UX flows from meta issue
Search or filter to slow-querying rules and bulk disable them
Search for rules with similar meta data (tags, tactic, etc.)
Search for failing rule and review log history to find issue
Confirm a rule was running during specific time, or review log at specific point in time

## Columns
The columns will be dependent on the solution.

**Not in scope**
- Editing connectors
- Changes to the create rule flow
- any fancy visualizations (for example indicators of how the alerting system is doing) 
- KPI Metrics for on top of the Rules page

**Outstanding requirement questions**
- Not sure if monitoring needs to be in its own tab (as Security solutions today) vs. combined tab view

## Wireframes
- [Rule monitoring v3 Whimsical (most-up-to-date)](https://whimsical.com/rule-monitoring-v3-65o1vqnn937FxbAuXPWQwL)

## Designs
- [Rule management MVP](https://www.figma.com/file/fGlLwahFKcCH9mnkrCz8Dw/7.16-Rule-Management-Version-MVP?node-id=0%3A1)
- [Rule management V1 (Future vision)](https://www.figma.com/file/KEgxx2B9J15i9uH3B50mq2/7.16-Rule-Management-Version-1?node-id=223%3A71326)

## Resources
- Import / Export Rules
[Smart Rule Import and Subscription #546](https://github.com/elastic/siem-team/issues/546)

**Comment by katrin-freihofner** [comment]
Related: https://github.com/elastic/kibana/issues/110604

**Comment by mdefazio** [comment]
Here's a quick stab at the Observability view.  

![image](https://user-images.githubusercontent.com/3756330/132353876-eeda2200-ed35-4f6a-9c7f-bf51badcf29b.png)

**Notes:**
- Removed columns carried over from Security: `risk score`, `severity`, `version`, `last updated`.  
- Activated column is labeled 'Enabled' 
- Including tags, though these may not be needed?
- I added the Rule type underneath the rule name.  There is more variance here on the Observability side than Security.  In security, this is only Elastic or Custom (correct?) and shown as a toggle.  I am not including this as it's own column because I didn't see value in being able to sort by rule type.  However, we do have a filter dropdown where the user can choose which types to show.

**To do:** 
- Still need to confirm rule execution statuses (Succeeded, Failed, etc.) vs Stack execution statuses. Previous Observability users would expect the statuses from Stack, so if choose to adopt the Security set, we may need some help options.

**Comment by mdefazio** [comment]
Next steps: 
- Get confirmation on statuses: Mike P, Gidi/Mike C, Jason/Cyrille
- How to show muting in UI of Security/Observ rule table
- Rule detail view for Observability
- Empty state for Observability
- Auto refresh settings
- Import / Export for Observability

**Comment by yiyangliu9286** [comment]
Thanks so much for the update @mdefazio, this looks great!

For Security Rules management table, I think the columns are correct. The only question that I have is the format for `Last run` column, now in-product it uses "11 minutes ago" for example, not sure if timestamp is intuitive enough for them to sort. Other than that I think it all looks great.

**Comment by mdefazio** [comment]
> The only question that I have is the format for Last run column

Yes...good catch.  I had updated it on the Stack mockup, but not everywhere else.  I'll update this.

**Comment by mdefazio** [comment]
### Latest Stack Rule management screens:

Just posting these for visibility.  Minor changes since last update.  I am showing 2 options for row overflow menu where the rule statuses are exposed at the root level, or behind a sub menu.  We could choose to omit this completely at the row leve, however, we would still need to determine this pattern for bulk action menu.

For bulk action menu, showing a possible solution when choosing rules with different statuses (and how to show which are selected).  

**Onboarding:** No rules have been installed yet
![image](https://user-images.githubusercontent.com/3756330/135117232-a726f921-c435-48ba-abe1-907b544cf47a.png)


**List view:** Rules have been installed
![image](https://user-images.githubusercontent.com/3756330/135117269-a43b6ddc-7b87-4cee-8e83-bd1f0a2552dc.png)

**Bulk actions:** Select multiple rules and perform an action from bulk menu
![image](https://user-images.githubusercontent.com/3756330/135117430-9c812111-90c8-4413-b80a-06f3e966579e.png)

**No data or results:** Change filters or search that returns no results
![image](https://user-images.githubusercontent.com/3756330/135117571-6586b9a0-67ce-44ec-b29b-e13d97a648bc.png)

**Comment by mdefazio** [comment]
The stack effort for this has shifted to be specific to this issue: https://github.com/elastic/kibana/issues/111805

**Comment by katrin-freihofner** [comment]
@yiyangliu9286 thanks for providing this update. Something I noticed is the alignment of numbers in this table. We usually right-align numbers, so they are easier to compare.
